server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nmqhoan/spring-cloud-config
          search-paths:
            - 'config-files/*service'
            - 'config-files'
          clone-on-start: true